# Generated by Django 5.2.4 on 2025-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
