# Generated by Django 5.2.4 on 2025-07-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_transaction_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sim_slot',
            field=models.CharField(choices=[('sim1', 'Sim1'), ('sim2', 'Sim2')], default='sim1', max_length=10),
        ),
    ]
