# Generated by Django 5.2.4 on 2025-11-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('mpesa', 'M-PESA'), ('safaricom', 'Safaricom'), ('user', 'User'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
